#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#default:
#    path: /default
#    controller: App\Controller\DefaultController::index

afficher:
    path: /view/afficherliste
    controller: App\ViewController::afficherliste

accueil:
    path: /biblio/
    controller: App\Controller\BibliothequeController::index

# accueil2:
#     path: /home
#     controller: App\Controller\HomeController::index

# accueil3:
#     path: /
#     controller: App\Controller\HomeController::index

apropos:
    path: /home/apropos
    controller: App\Controller\HomeController::aPropos

contact:
    path: /home/contact
    controller: App\Controller\HomeController::contact

bob:
    path: /default
    controller: App\Controller\DefaultController::bob    

#actu:
#    path: /actu
#    controller: App\Controller\DefaultController::affichage